### ISSUE TITLE
Translations turn "yes" and "no" into "true" and "false"

### ISSUE THREAD

**Issue by karlhe** [fnando/i18n-js#15]
Whenever the lowercase word "yes" appears in the Rails language yaml (e.g. en.yml), and rake i18n:export is run, the resulting javascript translation will replace the word with "true". The same applies for "no" becoming false.

```
en:
    yes: yes
    no: no
    other: Yes
```

becomes

```
{"en":{"true":"true","false":"false","other":"Yes"}
```
