### ISSUE TITLE
How to deal with missing keys in JS output

### ISSUE THREAD

**Issue by johnnyshields** [fnando/i18n-js#223]
I've seen issues where if I have a nested group of keys and only one of those keys is defined, sometimes it forces the whole group to be null in JS:

**Input (YAML)**

``` yml
en:
   foo:
     bar: "Bar"
     baz: "Baz"

ja:
   foo:
     bar: "Bar"
```

**Current Output**

``` js
{ "en": { "foo": {"bar": "Bar", "baz": "Baz"} } }
{ "ja": { "foo": null } }
```

**Expected Output**

``` js
{ "en": { "foo": {"bar": "Bar", "baz": "Baz"} } }
{ "ja": { "foo": {"bar": "Bar"} } }
```

It also might be best to throw a `"key not found"` warning during the compilation step, as currently we have to discover this while testing the app :frowning: !
