### ISSUE TITLE
Where can I get list of supported locales

### ISSUE THREAD

**Issue by mshndev** [fnando/i18n-js#236]
I need Czech locale.

I tried three variants: 

``` YAML
- file: "public/javascripts/i18n/cs.js"
  only: "cs.*"

- file: "public/javascripts/i18n/cs.js"
  only: "cz.*"

- file: "public/javascripts/i18n/cs.js"
  only: "cs-CZ.*"
```

In all these cases I got an error `TypeError: no implicit conversion of nil into Hash`
Thanks!
