### ISSUE TITLE
Fallbacks don't appear to be working correctly.

### ISSUE THREAD

**Issue by Senjai** [fnando/i18n-js#297]
```yaml
translations:
- file: "public/javascripts/translations.js"
  only: "*.js"
```

Is my i18n-js file. In my en.yml, I have js.test defined, in my it.yml, I dont have js defined at all. In the developer console:
```js
I18n.t("js.test")
> "This is a test"
I18n.locale = "it"
> "it"
I18n.t("js.test")
> "[missing "it.js.test" translation]"
```

I would expect the last method call to yield the same as the first. Could anyone shed any light on this?

I have tried setting fallbacks to a locale manually in the configuration file to no avail as well.
