### ISSUE TITLE
Auto-generate separated files

### ISSUE THREAD

**Issue by mainameiz** [fnando/i18n-js#343]
Is it supported to auto-generate separate files provided in i18n-js.yml or not?
It's not fun to run `rake i18n:js:export` every time :-(.

I did not find any info in docs about this feature.

**Comment by PikachuEXE** [comment]
What do you mean by "auto-generate"?
There is a `I18n::JS::Middleware` in README.
Not sure if that's what you want.

**Comment by mainameiz** [comment]
Consider I have these lines in config

```
translations:
 - file: "i18n/admin.js"
   only: ["*.js.admin", "*.js.shared", "*.activerecord.models", "*.activerecord.attributes"]

translations:
 - file: "i18n/moderation.js"
   only: ["*.js.moderation", "*.js.shared", "*.quest_page"]
```

I want just to use it in application.js this way

```coffee
#= require 'i18n/admin'
```

and in another file

```coffee
#= require 'i18n/moderation'
```

without manually generating it with `rake i18n:js:export`. Is it possible?
