### ISSUE TITLE
I18n::JS::Middleware autogeneration not working in Rails 4.2.3

### ISSUE THREAD

**Issue by seoyoochan** [fnando/i18n-js#350]
I added `config.middleware.use I18n::JS::Middleware` in `development.rb`
but it does not work in rails 4.2.3
can someone reproduce this?

**Comment by PikachuEXE** [comment]
Please provide more info first
such as versions of common gems like `rails` and `sprockets`

Describe what is expected and what actually happens

**Comment by alvinsj** [comment]
@seoyoochan @PikachuEXE I have similar issue with the use of config/i18n-js.yml.
This is how I reproduce:

In `config/i18n-js.yml`:
```yaml
translations:
  - file: "public/javascripts/i18n/a.translations.js"
    only: ["*.a"]
  - file: "public/javascripts/i18n/b.translations.js"
    only: ["*.b"]
```
0. At first, everything is working. 
1. Remove what is in `public/javascripts/i18n/`
2. Refresh the app, and see `missing translations` error.
3. Remove `tmp/cache/i18n-js.yml`
4. Refresh the app again, It works now by newly generated files as specified in `config/i18n-js.yml`
