### ISSUE TITLE
Cache is not expired when config/i18n-js.yml is changed

### ISSUE THREAD

**Issue by joakimk** [fnando/i18n-js#355]
We use a config file that looks like this:

``` yaml
translations:
  - only: "*.date.*" 
  - only: "*.time.*"
  - only: "*.admin.javascript.*"
```

And so on.

When adding a new line to this file we have to run `rm -rf tmp/cache/assets` (e.g. "rake assets:clobber") to have the translations be available.

It seems like this is a normal usecase which should not require a manual cache wipe.
