### ISSUE TITLE
Asset pipeline not working

### ISSUE THREAD

**Issue by brauliobo** [fnando/i18n-js#356]
`rake i18n:js:export` works fine, but if I delete translations, and try a HTTP request to `/assets/javascripts/i18n/pt_BR.js` (or any other locale), I always get 404 error.

The config is as follows:

``` yml
<% plugins = Noosfero::Plugin.all.map{ |p| p.gsub(/Plugin$/, '').underscore } %>

translations:
- file: "public/javascripts/i18n/%{locale}.js"
  except: <%= plugins.map{ |p| "*.#{p}_plugin" }.inspect %>

<% plugins.each do |plugin| %>
- file: "public/javascripts/i18n/<%=plugin%>/%{locale}.js"
  only: "*.<%=plugin%>_plugin"
<% end %>
```

Using rails 4.2.4

**Comment by brauliobo** [comment]
I've tried this also, but it didn't helped:
```yml
<% plugins = Noosfero::Plugin.all.map{ |p| p.gsub(/Plugin$/, '').underscore } %>

translations:
<% I18n.available_locales.each do |locale| %>
  - file: "public/javascripts/i18n/<%=locale%>.js"
    except: <%= plugins.map{ |p| "*.#{p}_plugin" }.inspect %>

  <% plugins.each do |plugin| %>
  - file: "public/javascripts/i18n/<%=plugin%>/<%=locale%>.js"
    only: "*.<%=plugin%>_plugin"
  <% end %>
<% end %>
```
