### ISSUE TITLE
Locales generation

### ISSUE THREAD

**Issue by dusancymorek** [fnando/i18n-js#382]
Hello, 

I don't know if I am doing something wrong, but *.js locale files are not generated properly. In our project we currently have two locales (en, sk), so our `i18n-js.yml` config contains following:

```
translations:
- file: "app/assets/javascripts/i18n/en.js"
  only: "en.*"
- file: "app/assets/javascripts/i18n/sk.js"
  only: "sk.*"
```

The `en.js` is generated properly, however `sk.js` fills in all locales with Slovak translations. Therefore, even if `I18n.currentLocale()` returns correct locale set in Rails (4.2.5), every `I18n.t()` call returns Slovak translation of specified key.

Thanks for any tips.

**Comment by PikachuEXE** [comment]
You said:
```
sk.js fills in all locales with Slovak translations
```
Can you explain more why this is a problem?

I parse the above statement as:
```js
// sk.js
I18n.locales = {"sk": {"slovak": "translations"}}
// Not exact code, just try to present the expected content here :P
```

**Comment by dusancymorek** [comment]
en.js

```
I18n.translations || (I18n.translations = {});
I18n.translations["en"] = I18n.extend((I18n.translations["en"] || {}), {"key1" : {"subkey1": "value_en"}});
I18n.translations["ru"] = I18n.extend((I18n.translations["ru"] || {}), {});
I18n.translations["en-GB"] = I18n.extend((I18n.translations["en-GB"] || {}), {});
...
```

sk.js

```
I18n.translations || (I18n.translations = {});
I18n.translations["sk"] = I18n.extend((I18n.translations["sk"] || {}), {"key1" : {"subkey1": "value_sk"}});
I18n.translations["en"] = I18n.extend((I18n.translations["en"] || {}), {"key1" : {"subkey1": "value_sk"}});
I18n.translations["ru"] = I18n.extend((I18n.translations["ru"] || {}), {"key1" : {"subkey1": "value_sk"}});
I18n.translations["en-GB"] = I18n.extend((I18n.translations["en-GB"] || {}), {"key1" : {"subkey1": "value_sk"}});
...

```

**Comment by PikachuEXE** [comment]
Have you tried changing the value in `only` node for `sk.js`?
Try to change it to `en.*` or `ru.*` to see if it generates translations as expected

**Comment by dusancymorek** [comment]
If I change it to `en.*` or `ru.*`, everything works as expected.

**Comment by PikachuEXE** [comment]
Can you paste a portion of your translations for `sk` and `en`?
Maybe there is something special that triggers this issue?
I can't really determine without the translation right now :)

**Comment by dusancymorek** [comment]
Sure, here is a part of "comments" translations:

```yaml
en:
  comments:
    errors:
      edit_banned:      "You can't edit banned comment."
      reply_banned:     "You can't reply to banned comment."
    labels:
      add_comment:      "Add comment"
      author:           "Author"
      comments:         "Comments"
      reply:            "Reply"
    text:
      banned:           "Comment has been deleted due to inappropriate content."
      remove_success:   "Comment has been successfully removed."
```

```yaml
sk:
  comments:
    errors:
      edit_banned:      "Nemôžete editovať zakazáný komentár."
      reply_banned:     "Nemôžete odpovedať na zakázaný komentár."
    labels:
      add_comment:      "Pridať komentár"
      author:           "Zadávateľ"
      comments:         "Komentáre"
      reply:            "Odpovedať"
    text:
      banned:           "Komentár bol zmazaný pre nevhodný obsah."
      remove_success:   "Komentár bol úspešne odstránený."
```
