### ISSUE TITLE
I18n-js does not support symbol references in i18n translations

### ISSUE THREAD

**Issue by lowjoel** [fnando/i18n-js#392]
Given

``` yaml
en:
  common:
    test: 'Some string'
  javascript:
   something: :'common.test'
```

I see `I18n.t('javascript.something')` returning 'common.test', but the Ruby implementation will return 'Some string' because it resolves symbol references.
