### ISSUE TITLE
Filtering using Asset Pipelines

### ISSUE THREAD

**Issue by nitsujri** [fnando/i18n-js#400]
Thanks for this amazing Gem!

I've been through all the docs + issues + code and I'm quite confused on how to filter keys. Currently I have tried these ways:

    # i18n-js.yml
    - file: "app/assets/javascripts/i18n/translations.js"
      only: "studio_dash.*"

    # i18n-js.yml
    - only: "studio_dash.*"
      
There's a number of competing issues that make me unsure this is the correct way to go about it.

Am I forced to use the middleware or can I keep it in the pipeline?

**Comment by PikachuEXE** [comment]
Can you try `*.studio_dash.*`?
We change to use that format since some user want to filter by locale as well
Which is a valid case

**Comment by nitsujri** [comment]
@PikachuEXE thanks for the super fast response. Here's my `i18n-js.yml`

```
translations:
  - only: "*.studio_dash.*"

translations:
  - file: "app/assets/javascripts/i18n/translations.js"
    only: "*.studio_dash.*"
```

I tried both and `filtered-<fingerprint>.js` comes up with 100% of my keys. The `translations-<fingerprint>.js` file is empty though?
