### ISSUE TITLE
Obscure sentence in README

### ISSUE THREAD

**Issue by chongkai** [fnando/i18n-js#403]
Except the option file, since all translations are required by adding //= require i18n/translations.

A little more explanation is needed on this sentence. I really don't understand it.

**Comment by PikachuEXE** [comment]
That means the node `file` has no effect when using asset pipeline
```
translations:
- file: 'public/javascripts/path-to-your-messages-file.js'
  only: '*.date.formats'
- file: 'public/javascripts/path-to-your-second-file.js'
  only: ['*.activerecord', '*.admin.*.title']
```
