### ISSUE TITLE
Fallback locales work incorrectly

### ISSUE THREAD

**Issue by kikonen** [fnando/i18n-js#414]
I'm trying to do following

```
translations:
  - file: 'app/assets/javascripts/i18n/translations_de.js'
    only: ['en.js.*', 'de.js.*']
  - file: 'app/assets/javascripts/i18n/translations_en.js'
    only: 'en.js.*'
  - file: 'app/assets/javascripts/i18n/translations_fi.js'
    only: ['en.js.*', 'fi.js.*']
```

"en" is fallback always. However, it seems that generated files contain always data for all locales, not only locale which I try to generate into file. It seems that all locales are pulled in via fallback locale merging logic in this gem, thus for every locale there is map filled with fallback translations from "en" locale.
