### ISSUE TITLE
How to use HTML inside locale?

### ISSUE THREAD

**Issue by igorlemosvicente** [fnando/i18n-js#485]
Is it possible to pass or use html to the .yml files?

Example:
```yml
#test.yml
en:
  test: A message %{html}
  another_test: Another message <b>with html</b>
```
```javascript
I18n.t('teste', { html: <b>with html</b> }) //> A message <b>with html</b>
I18n.t('another.teste') //> Another message <b>with html</b>
```
