### ISSUE TITLE
Can you use multiple files for one locale ?

### ISSUE THREAD

**Issue by QuentinNev** [fnando/i18n-js#532]
Hi !

We use this library with [React-Native-Languages](https://github.com/react-native-community/react-native-languages) and I would like to know if it's possible to split one locale file into multiples bits related to a particular screen. To be simple, it would be great if we could : `i18n.t( key, screen, { language: i18n.currentLocale() } )`

Translations would be easier to manage, currently I use prefix and suffix to differentiate them. As it's stored in json files, you can't format nor comment anything inside it which leads to a very long file where it's difficult to identify what is what (at least for me).

Is there already a feature that fill my desire ?

Thank you in advance.

**Comment by PikachuEXE** [comment]
I guess it would be something like:
```yaml
translations:
- file: 'public/javascripts/translations/pages/page_type_one'
  only: '*.app.pages.page_type_one.*'
- file: 'public/javascripts/translations/pages/page_type_two'
  only: '*.app.pages.page_type_two.*'
- file: 'public/javascripts/translations/pages/all_pages_shared'
  only: '*.app.pages.all_pages_shared.*'
```

Not sure how you use this library so can't give more specific suggestion
Provide more details if you have more questions
