### ISSUE TITLE
Support for i18n-inflector-rails inflections

### ISSUE THREAD

**Issue by kueda** [fnando/i18n-js#550]
Any chance for supporting inflections used for [i18n-inflector-rails](https://github.com/siefca/i18n-inflector-rails)? This would mean that if there was a source translation like 

```yaml
en:
  apple: apple
  grapefruit: grapefruit
  i18n:
    inflections:
      :@gender:
      m: male
      f: female
      n: neuter
      apple: :@n
      grapefruit: :@n
fr:
  apple: pomme
  grapefruit: pamplemousse
  i18n:
    inflections:
      :@gender:
      m: male
      f: female
      n: neuter
      apple: :@f
      grapefruit: :@m
```

and a key like `a_fruit` with a French translation like `@gender{m:un|f:une|un(e)} %{fruit}`, you could use the translation like `I18n.t("a_fruit", {fruit: I18n.t("apple"), gender: "apple"})` would yield "une pomme" and `I18n.t("a_fruit", {fruit: I18n.t("grapefruit"), gender: "grapefruit"})` would yield "un pamplemousse."

If that seems too coupled to that gem, how do people usually deal with gendered nouns in i18n-js?
