### ISSUE TITLE
Doesn't follow only syntax in config

### ISSUE THREAD

**Issue by Dreamersoul** [fnando/i18n-js#557]
Here is my `i18n-js.yml` file contents:

```yml
translations:
  - file: "app/assets/javascripts/i18n/translations.js"
  - only: ['*.vue', '*.activerecord.enums']
```
however when i go to the following file `app/assets/javascripts/i18n/translations.js`
all the strings are showing even the ones that are not in the only rule such as [Faker](https://github.com/faker-ruby/faker) translations making the file insanely large and exposing translations for any user to see if they check the console.
