### ISSUE TITLE
Our i18n-js.yml gets parsed 240 times on first page load

### ISSUE THREAD

**Issue by Shyked** [fnando/i18n-js#592]
We are using the ERB syntax to generate a configuration file reflecting the languages list we have in our database.

```
fallbacks: false

translations:
  - file: "app/assets/javascripts/i18n/base.js"
    only: "base.*"
    pretty_print: true
<% Language.all.each do |language| %>
  - file: <%= "app/assets/javascripts/i18n/#{language.code}.js" %>
    only: <%= "#{language.code}.*" %>
    pretty_print: true
<% end %>
  - file: <%= "app/assets/javascripts/i18n/en.js" %>
    only: <%= "en.*" %>
    pretty_print: true
```

We noticed that this configuration is causing 240 calls to our database coming from i18n-js.

In `/lib/i18n/js.rb`, I see the `config` function is called multiple times, and everytime it performs a new `ERB.new(File.read(config_file_path)).result`.

Is there a way to avoid this behavior, maybe a workaround, or is there something we're not doing correctly?

We're on i18n-js 3.3.0, I didn't try the latest version yet but after looking at the `js.rb` file I assumed the behavior would stay the same as the config is not cached.
