### ISSUE TITLE
Unused translations are in final bundle

### ISSUE THREAD

**Issue by ops1ops** [fnando/i18n-js#613]
Hey, recently i was investigating my final bundle size and noticed that translations.js size is huge and it doesnt depend on which bundle i use (i created 2 bundles with different components using i18n - they used different translations),  so i have a question, is there any way to decrease translations.js size by spliting it depending on namespaces, files etc. or some kind of lazy loading?

**Comment by PikachuEXE** [comment]
I have `config/i18n-js.yml` with:
```yaml
translations:
  - only:
    - "*.js.*"

    # Since there are only a few entries in some already used scopes
    # Allowing these to be output
    - "*.actions.defaults.*"
    - "*.formats.datetime.*"
    - "*.formats.sentence.*"
    # Too time consuming to these entries into specific namespace
    - "*.app_resources.some_resources.*"
    - "*.website_pages.*.js.*"
    - "*.components.main_navbar.universal_search_bar.*"
```

This way only the useful translations would be exported.
But I don't know your setup so this might not work for you. Try it first :)
