### ISSUE TITLE
Bug:  fails with no-such-method error when translation key is an integer

### ISSUE THREAD

**Issue by honzasterba** [fnando/i18n-js#639]
## Description

fails with an exception when generating from translation file like this:

```yaml
    errors:
      to_homepage: Back to homepage
      400: Invalid request
      404: Page not found
```

## How to reproduce

run json generator

## Software:

- Gem version: 4.0.0.alpha2
- Ruby version: 3.0.3
