### ISSUE TITLE
Bug: i18n lint fails when using plugins

### ISSUE THREAD

**Issue by msayed98** [fnando/i18n-js#705]
## Description

running `i18n lint:translations` fails when using plugins in the config file with `config has unexpected keys: [:export_files] (I18nJS::Schema::InvalidError)`
config file:
```yml
translations:
  - file: app/assets/javascripts/translations.json
    patterns:
      - "*"
export_files:
  enabled: true
  files:
    - template: config/i18n.erb
      output: "%{dir}/%{base_name}.js"
```

## Software:

- Gem version: 4.2.2
- Ruby version: 2.7.6
